import { useEffect, useState } from 'react';
import { requirementsAPI } from '../../services/api';

function RequirementsList() {
  const [requirements, setRequirements] = useState([]);
  const [state, setState] = useState({ loading: true, error: '', saving: '' });
  const load = () => requirementsAPI.getAll().then((data) => setRequirements(data.requirements || [])).catch((error) => setState((current) => ({ ...current, error: error.response?.data?.message || 'Unable to load requirements.' }))).finally(() => setState((current) => ({ ...current, loading: false })));
  useEffect(() => { load(); }, []);
  const updateStatus = async (id, status) => { setState((current) => ({ ...current, saving: id })); try { const data = await requirementsAPI.updateStatus(id, status); setRequirements((current) => current.map((item) => item._id === id ? data.requirement : item)); } catch (error) { setState((current) => ({ ...current, error: error.response?.data?.message || 'Unable to update status.' })); } finally { setState((current) => ({ ...current, saving: '' })); } };
  const pendingCount = requirements.filter((item) => item.status === 'Pending').length;
  const activeCount = requirements.filter((item) => item.status === 'In Progress').length;
  const completedCount = requirements.filter((item) => item.status === 'Completed').length;
  if (state.loading) return <div className="admin-empty-state">Loading requirements...</div>;
  if (state.error && requirements.length === 0) return <div className="admin-empty-state admin-empty-state--error">{state.error}</div>;
  return <section className="requirements-page"><header className="admin-data-header"><div><p className="admin-data-header__eyebrow">WORK QUEUE / CLIENT REQUESTS</p><h2>Requirements management</h2><p>Track incoming requests and keep their progress visible.</p></div><div className="admin-data-header__total"><strong>{requirements.length}</strong><span>Total requests</span></div></header><div className="admin-data-summary"><div><span>Pending review</span><strong>{pendingCount}</strong></div><div><span>In progress</span><strong>{activeCount}</strong></div><div><span>Completed</span><strong>{completedCount}</strong></div></div>{state.error && <div className="admin-data-alert">{state.error}</div>}{requirements.length === 0 ? <div className="admin-empty-state"><span>◇</span><h3>No requirements yet</h3><p>Requests submitted by users will appear here.</p></div> : <div className="requirements-list">{requirements.map((item, index) => <article className="requirement-admin-card" key={item._id}><div className="requirement-admin-card__top"><span className="requirement-admin-card__index">{String(index + 1).padStart(2, '0')}</span><span className={`priority-badge priority-badge--${item.priority.toLowerCase()}`}>{item.priority} priority</span><span className={`request-status request-status--${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span></div><div className="requirement-admin-card__content"><div><p className="requirement-admin-card__category">{item.category || 'General'}</p><h3>{item.title}</h3><p className="requirement-admin-card__description">{item.description}</p></div><div className="requirement-admin-card__owner"><span className="requirement-admin-card__avatar">{item.user?.name?.charAt(0).toUpperCase() || '?'}</span><div><strong>{item.user?.name || 'Unknown user'}</strong><small>{item.user?.email || 'No email available'}</small></div></div></div><footer className="requirement-admin-card__footer"><span>{new Date(item.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span><label>Update status<select value={item.status} disabled={state.saving === item._id} onChange={(event) => updateStatus(item._id, event.target.value)}><option>Pending</option><option>In Progress</option><option>Completed</option></select></label></footer></article>)}</div>}</section>;
}
export default RequirementsList;